# Generated by Django 5.1 on 2024-08-29 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="enrollment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_ticket",
                to="enrollments.enrollment",
            ),
        ),
    ]
