# Generated by Django 5.1 on 2024-08-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='foto_perfil.webp', null=True, upload_to='profile_pics'),
        ),
    ]
