# Generated by Django 5.1 on 2024-08-29 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
